/*
1035 Password （20 分）
To prepare for PAT, the judge sometimes has to generate random passwords for the users. The problem is that there are always some confusing passwords since it is hard to distinguish 1 (one) from l (L in lowercase), or 0 (zero) from O (o in uppercase). One solution is to replace 1 (one) by @, 0 (zero) by %, l by L, and O by o. Now it is your job to write a program to check the accounts generated by the judge, and to help the juge modify the confusing passwords.

Input Specification:
Each input file contains one test case. Each case contains a positive integer N (≤1000), followed by N lines of accounts. Each account consists of a user name and a password, both are strings of no more than 10 characters with no space.

Output Specification:
For each test case, first print the number M of accounts that have been modified, then print in the following M lines the modified accounts info, that is, the user names and the corresponding modified passwords. The accounts must be printed in the same order as they are read in. If no account is modified, print in one line There are N accounts and no account is modified where N is the total number of accounts. However, if N is one, you must print There is 1 account and no account is modified instead.

Sample Input 1:
3
Team000002 Rlsp0dfa
Team000003 perfectpwd
Team000001 R1spOdfa
Sample Output 1:
2
Team000002 RLsp%dfa
Team000001 R@spodfa
Sample Input 2:
1
team110 abcdefg332
Sample Output 2:
There is 1 account and no account is modified
Sample Input 3:
2
team110 abcdefg222
team220 abcdefg333
Sample Output 3:
There are 2 accounts and no account is modified

*/
/*
总结:就是检查然后修改
*/
/*
单词:
prepare 准备
judge 判断
confusing 乱
*/
#include<iostream>
#include<cstdio>
#include<unordered_map>
#include<cctype>
#include<string>
#include<algorithm>
#include<vector>
#include<cstring>
#include<cmath>

using namespace std;
struct Node{
    string name;
    string password;
};

vector<Node> ve;

main(){
#ifdef LOCAL
    freopen("input.in","r",stdin);
    freopen("output.out","w",stdout);
#endif
    int N; cin >> N;
    int cnt;
    for(int i = 0;i<N;i++){
        int ok = 1;
        string name,password; cin >> name >> password;
        int password_len = password.size();
        for(int z = 0;z<password_len;z++){
            if(password[z] == '1'){password[z] = '@';ok = 0;}
            if(password[z] == '0'){password[z] = '%';ok = 0;}
            if(password[z] == 'l'){password[z] = 'L';ok = 0;}
            if(password[z] == 'O'){password[z] = 'o';ok = 0;}
        }
        if(ok == 0){Node node; node.name = name; node.password = password; ve.push_back(node);}
    }
    int ve_len = ve.size();
    if(ve_len != 0){
        cout << ve_len << endl;
        for(int i = 0;i<ve_len;i++){
            cout << ve[i].name << " " << ve[i].password << endl;
        }
    }
    else{
        if(N == 1){cout << "There is 1 account and no account is modified";}
        else{cout << "There are " << N << " accounts and no account is modified";}
    }
    return 0;
}